# Generated by Django 2.2.4 on 2021-08-10 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(default=datetime.date.today, verbose_name='Workout Date')),
                ('workout_time', models.PositiveIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100'), (110, '110'), (120, '120')], default=60, verbose_name='Workout Duration')),
                ('muscle_group', models.TextField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('abs', 'Abs'), ('cardio', 'Cardio')], verbose_name='Muscle Group')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=100, verbose_name='Routine Name')),
                ('num_sets', models.PositiveSmallIntegerField(verbose_name='Number of sets')),
                ('num_reps', models.PositiveSmallIntegerField(verbose_name='Number of reps')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.Workout')),
            ],
        ),
    ]
