# Generated by Django 2.2.4 on 2021-07-28 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(default=datetime.date.today, verbose_name='Workout Date')),
                ('workout_time', models.DurationField(choices=[(datetime.timedelta(seconds=600), '10'), (datetime.timedelta(seconds=1200), '20'), (datetime.timedelta(seconds=1800), '30'), (datetime.timedelta(seconds=2400), '40'), (datetime.timedelta(seconds=3000), '50'), (datetime.timedelta(seconds=3600), '60'), (datetime.timedelta(seconds=4200), '70'), (datetime.timedelta(seconds=4800), '80'), (datetime.timedelta(seconds=5400), '90'), (datetime.timedelta(seconds=6000), '100'), (datetime.timedelta(seconds=6600), '110'), (datetime.timedelta(seconds=7200), '120')], default=datetime.timedelta(seconds=3600), verbose_name='Workout Duration')),
                ('muscle_group', models.TextField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('abs', 'Abs'), ('cardio', 'Cardio')], verbose_name='Muscle Group')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_name', models.CharField(max_length=100, verbose_name='Routine Name')),
                ('num_sets', models.PositiveSmallIntegerField(verbose_name='Number of sets')),
                ('num_reps', models.PositiveSmallIntegerField(verbose_name='Number of reps')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.Workout')),
            ],
        ),
    ]
