# Generated by Django 2.2.4 on 2021-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_time',
            field=models.PositiveIntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100'), (110, '110'), (120, '120')], default=60, verbose_name='Workout Duration'),
        ),
    ]
